# Generated by Django 4.0.6 on 2023-03-10 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tripPlanner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='rate',
            new_name='rating',
        ),
    ]
