# Generated by Django 4.0.6 on 2023-03-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripPlanner', '0003_alter_feedback_feedbackid_alter_place_locationid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='img',
            field=models.CharField(max_length=255),
        ),
    ]
