# Generated by Django 4.0.6 on 2023-03-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripPlanner', '0005_alter_place_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='img',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
