# Generated by Django 4.0.6 on 2023-03-12 16:12

from django.db import migrations, models
import tripPlanner.models


class Migration(migrations.Migration):

    dependencies = [
        ('tripPlanner', '0006_alter_place_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=tripPlanner.models.filepath),
        ),
    ]
